package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1



/**
 * Admins generated by hbm2java
 */
public class Admins  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;
     private boolean insertPriv;
     private boolean selectPriv;
     private boolean updatePriv;
     private boolean deletePriv;

    public Admins() {
    }

    public Admins(String name, String username, String password, boolean insertPriv, boolean selectPriv, boolean updatePriv, boolean deletePriv) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.insertPriv = insertPriv;
       this.selectPriv = selectPriv;
       this.updatePriv = updatePriv;
       this.deletePriv = deletePriv;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isInsertPriv() {
        return this.insertPriv;
    }
    
    public void setInsertPriv(boolean insertPriv) {
        this.insertPriv = insertPriv;
    }
    public boolean isSelectPriv() {
        return this.selectPriv;
    }
    
    public void setSelectPriv(boolean selectPriv) {
        this.selectPriv = selectPriv;
    }
    public boolean isUpdatePriv() {
        return this.updatePriv;
    }
    
    public void setUpdatePriv(boolean updatePriv) {
        this.updatePriv = updatePriv;
    }
    public boolean isDeletePriv() {
        return this.deletePriv;
    }
    
    public void setDeletePriv(boolean deletePriv) {
        this.deletePriv = deletePriv;
    }




}


