package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import dao.AdminsDao;



/**
 * Admins generated by hbm2java
 */
@ManagedBean
//@SessionScoped
public class Admins implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;
     private boolean insertPriv;
     private boolean selectPriv;
     private boolean updatePriv;
     private boolean deletePriv;
     private ArrayList<Admins> adminsList;
     AdminsDao dao = new AdminsDao();
     

    public Admins() {
    }

    public Admins(String name, String username, String password, boolean insertPriv, boolean selectPriv, boolean updatePriv, boolean deletePriv) {
       this.name = name;
       this.username = username;
       this.password = password;
       this.insertPriv = insertPriv;
       this.selectPriv = selectPriv;
       this.updatePriv = updatePriv;
       this.deletePriv = deletePriv;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isInsertPriv() {
        return this.insertPriv;
    }
    
    public void setInsertPriv(boolean insertPriv) {
        this.insertPriv = insertPriv;
    }
    public boolean isSelectPriv() {
        return this.selectPriv;
    }
    
    public void setSelectPriv(boolean selectPriv) {
        this.selectPriv = selectPriv;
    }
    public boolean isUpdatePriv() {
        return this.updatePriv;
    }
    
    public void setUpdatePriv(boolean updatePriv) {
        this.updatePriv = updatePriv;
    }
    public boolean isDeletePriv() {
        return this.deletePriv;
    }
    
    public void setDeletePriv(boolean deletePriv) {
        this.deletePriv = deletePriv;
    }

    @Override
    public String toString() {
        return "id=" + id + ", name=" + name + ", username=" + username + ", password=" + password + ", insertPriv=" + insertPriv + ", selectPriv=" + selectPriv + ", updatePriv=" + updatePriv + ", deletePriv=" + deletePriv + "\n";
    }
    
    public List<Admins> getAll() {
        return dao.getAll();
    }
    
    public String getById() {
        Admins admin = dao.getById(id);
        this.id = admin.getId();
        this.name = admin.getName();
        this.username = admin.getUsername();
        this.password = admin.getPassword();
        this.insertPriv = admin.isInsertPriv();
        this.selectPriv = admin.isSelectPriv();
        this.updatePriv = admin.isUpdatePriv();
        this.deletePriv = admin.isDeletePriv();
        
        return "./edit_admins.xhtml";
    }
    
    public boolean login() {
        Admins admin = dao.getByUsernameAndPassword(username, password);
        this.setId(admin.getId());
        this.setName(admin.getName());
        this.setUsername(admin.getUsername());
        this.setPassword(admin.getPassword());
        this.setInsertPriv(admin.isInsertPriv());
        this.setSelectPriv(admin.isSelectPriv());
        this.setUpdatePriv(admin.isUpdatePriv());
        this.setDeletePriv(admin.isDeletePriv());
        
        return admin != null;
    }
    
    public String logout() {        
        return "/G2AirlineHibernate/faces/view/users.xhtml";
    }
    
    public String create() {
        boolean isCreated = dao.create(this);
        
        return isCreated ? "../admins.xhtml" : "./create_admins.xhtml";
    }

    public String update() {
        boolean isUpdated = dao.update(this);
        
        return isUpdated ? "../admins.xhtml" : "./edit_admins.xhtml";
    }
    
    public String delete() {
        boolean isDeleted = dao.delete(this);
        
        return isDeleted ? "../admins.xhtml" : "./edit_admins.xhtml";
    }
}


