package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1


import dao.FlightsDao;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Flights generated by hbm2java
 */
@ManagedBean
public class Flights  implements java.io.Serializable {


     private Integer id;
     private Airplanes airplanes;
     private Routes routes;
     private Date timeOfDeparture;
     private Set reservationses = new HashSet(0);
     
     FlightsDao dao = new FlightsDao();

    public Flights() {
    }

	
    public Flights(Airplanes airplanes, Routes routes, Date timeOfDeparture) {
        this.airplanes = airplanes;
        this.routes = routes;
        this.timeOfDeparture = timeOfDeparture;
    }
    public Flights(Airplanes airplanes, Routes routes, Date timeOfDeparture, Set reservationses) {
       this.airplanes = airplanes;
       this.routes = routes;
       this.timeOfDeparture = timeOfDeparture;
       this.reservationses = reservationses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Airplanes getAirplanes() {
        return this.airplanes;
    }
    
    public void setAirplanes(Airplanes airplanes) {
        this.airplanes = airplanes;
    }
    public Routes getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Routes routes) {
        this.routes = routes;
    }
    public Date getTimeOfDeparture() {
        return this.timeOfDeparture;
    }
    
    public void setTimeOfDeparture(Date timeOfDeparture) {
        this.timeOfDeparture = timeOfDeparture;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }

    public List<Flights> getAll() {
        return dao.getAll();
    }
    
    public String getById() {
        Flights flight = dao.getById(id);
        this.id = flight.getId();
        this.routes = flight.getRoutes();
        this.airplanes = flight.getAirplanes();
        this.timeOfDeparture = flight.getTimeOfDeparture();
        
        return "/edit_flights.xhtml";
    }
    
    public String create() {
        boolean isCreated = dao.create(this);
        
        return isCreated ? "superadmin" : "create_superadmin";
    }

    public String update() {
        boolean isUpdated = dao.update(this);
        
        return isUpdated ? "superadmin" : "edit_superadmin";
    }
    
    public String delete() {
        boolean isDeleted = dao.delete(this);
        
        return isDeleted ? "superadmin" : "edit_superadmin";
    }
}


