package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Flights generated by hbm2java
 */
public class Flights  implements java.io.Serializable {


     private Integer id;
     private Airplanes airplanes;
     private Routes routes;
     private Date timeOfDeparture;
     private Set reservationses = new HashSet(0);

    public Flights() {
    }

	
    public Flights(Airplanes airplanes, Routes routes, Date timeOfDeparture) {
        this.airplanes = airplanes;
        this.routes = routes;
        this.timeOfDeparture = timeOfDeparture;
    }
    public Flights(Airplanes airplanes, Routes routes, Date timeOfDeparture, Set reservationses) {
       this.airplanes = airplanes;
       this.routes = routes;
       this.timeOfDeparture = timeOfDeparture;
       this.reservationses = reservationses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Airplanes getAirplanes() {
        return this.airplanes;
    }
    
    public void setAirplanes(Airplanes airplanes) {
        this.airplanes = airplanes;
    }
    public Routes getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Routes routes) {
        this.routes = routes;
    }
    public Date getTimeOfDeparture() {
        return this.timeOfDeparture;
    }
    
    public void setTimeOfDeparture(Date timeOfDeparture) {
        this.timeOfDeparture = timeOfDeparture;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }




}


