package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1


import dao.ReservationsDao;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Reservations generated by hbm2java
 */
@ManagedBean
public class Reservations  implements java.io.Serializable {


     private Integer id;
     private Flights flights;
     private Users users;
     private boolean paid;
     private boolean active;
     private Set reservationsInfos = new HashSet(0);
     
     ReservationsDao dao = new ReservationsDao();

    public Reservations() {
    }

	
    public Reservations(Flights flights, Users users, boolean paid, boolean active) {
        this.flights = flights;
        this.users = users;
        this.paid = paid;
        this.active = active;
    }
    public Reservations(Flights flights, Users users, boolean paid, boolean active, Set reservationsInfos) {
       this.flights = flights;
       this.users = users;
       this.paid = paid;
       this.active = active;
       this.reservationsInfos = reservationsInfos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Flights getFlights() {
        return this.flights;
    }
    
    public void setFlights(Flights flights) {
        this.flights = flights;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public boolean isPaid() {
        return this.paid;
    }
    
    public void setPaid(boolean paid) {
        this.paid = paid;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public Set getReservationsInfos() {
        return this.reservationsInfos;
    }
    
    public void setReservationsInfos(Set reservationsInfos) {
        this.reservationsInfos = reservationsInfos;
    }

    public List<Reservations> getAll() {
        return dao.getAll();
    }
    
    public String getById() {
        Reservations reservation = dao.getById(id);
        this.id = reservation.getId();
        this.flights = reservation.getFlights();
        this.users = reservation.getUsers();
        this.paid = reservation.isPaid();
        this.active = reservation.isActive();
        
        return "./edit_reservations.xhtml";
    }

    public String create() {
        boolean isCreated = dao.create(this);
        
        return isCreated ? "../reservations.xhtml" : "./create_reservations.xhtml";
    }

    public String update() {
        boolean isUpdated = dao.update(this);
        
        return isUpdated ? "../reservations.xhtml" : "./edit_reservations.xhtml";
    }
    
    public String delete() {
        boolean isDeleted = dao.delete(this);
        
        return isDeleted ? "../reservations.xhtml" : "./edit_reservations.xhtml";
    }
}


