package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1

import dao.ReservationsDao;
import dao.ReservationsInfoDao;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * ReservationsInfo generated by hbm2java
 */
@ManagedBean
public class ReservationsInfo  implements java.io.Serializable {

     private Integer id;
     private int reservationId;
     private Reservations reservations;
     private String seatClass;
     private String name;
     private byte age;
     private String gender;
     private Long phoneNumber;
     
     ReservationsInfoDao dao = new ReservationsInfoDao();

    public ReservationsInfo() {
    }

	
    public ReservationsInfo(Reservations reservations, String seatClass, String name, byte age, String gender) {
        this.reservations = reservations;
        this.seatClass = seatClass;
        this.name = name;
        this.age = age;
        this.gender = gender;
    }
    public ReservationsInfo(Reservations reservations, String seatClass, String name, byte age, String gender, Long phoneNumber) {
       this.reservations = reservations;
       this.seatClass = seatClass;
       this.name = name;
       this.age = age;
       this.gender = gender;
       this.phoneNumber = phoneNumber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Reservations getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Reservations reservations) {
        this.reservations = reservations;
    }
    public String getSeatClass() {
        return this.seatClass;
    }
    
    public void setSeatClass(String seatClass) {
        this.seatClass = seatClass;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getAge() {
        return this.age;
    }
    
    public void setAge(byte age) {
        this.age = age;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public List<ReservationsInfo> getAll() {
        return dao.getAll();
    }
    
    public String getById() {
        ReservationsInfo reservationInfo = dao.getById(id);
        this.id = reservationInfo.getId();
        this.reservations = reservationInfo.getReservations();
        this.name = reservationInfo.getName();
        this.age = reservationInfo.getAge();
        this.gender = reservationInfo.getGender();
        this.phoneNumber = reservationInfo.getPhoneNumber();
        
        return "./edit_reservations_info.xhtml";
    }

    public String create() {
        boolean isCreated = dao.create(this);
        
        return isCreated ? "../reservations_info.xhtml" : "./create_reservations_info.xhtml";
    }

    public String update() {
        ReservationsDao reservationDao = new ReservationsDao();
        reservations = reservationDao.getById(reservationId);
        
        boolean isUpdated = dao.update(this);
        
        return isUpdated ? "../reservations_info.xhtml" : "./edit_reservations_info.xhtml";
    }
    
    public String delete() {
        boolean isDeleted = dao.delete(this);
        
        return isDeleted ? "../reservations_info.xhtml" : "./edit_reservations_info.xhtml";
    }
}


