package pojo;
// Generated Oct 10, 2022 3:35:36 PM by Hibernate Tools 4.3.1


import dao.UsersDao;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Users generated by hbm2java
 */
@ManagedBean
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String email;
     private String password;
     private String name;
     private Date dateOfBirth;
     private String gender;
     private String title;
     private long phoneNumber;
     private Set reservationses = new HashSet(0);
     
     UsersDao dao = new UsersDao();

    public Users() {
    }

	
    public Users(String username, String email, String password, String name, Date dateOfBirth, long phoneNumber) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.name = name;
        this.dateOfBirth = dateOfBirth;
        this.phoneNumber = phoneNumber;
    }
    public Users(String username, String email, String password, String name, Date dateOfBirth, String gender, String title, long phoneNumber, Set reservationses) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.name = name;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.title = title;
       this.phoneNumber = phoneNumber;
       this.reservationses = reservationses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public long getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Set getReservationses() {
        return this.reservationses;
    }
    
    public void setReservationses(Set reservationses) {
        this.reservationses = reservationses;
    }

    public List<Users> getAll() {
        return dao.getAll();
    }
    
    public Users getById() {
        return Users.class.cast(dao.getById(Users.class, id));
    }


}


